import type {Campaign,ChangeHistoryEntry,Finding,FindingAnswer,FindingFamily,FindingRequirement,RequirementState,Serializable,UserProfile} from '../types';
export const DUE_SOON_DAYS=7;
export const completedFor=(r:FindingRequirement,findings:Finding[])=>findings.filter(f=>f.requirementId===r.id&&f.origin==='PLANNED'&&f.recordStatus==='COMPLETED').length;
export const isSatisfied=(r:FindingRequirement,findings:Finding[])=>completedFor(r,findings)>=r.requiredCount;
export function requirementState(r:FindingRequirement,findings:Finding[],now=new Date()):RequirementState{if(isSatisfied(r,findings))return 'SATISFIED';if(now<new Date(r.periodStart))return 'UPCOMING';const due=new Date(r.dueDate);if(now>due)return 'OVERDUE';return (due.getTime()-now.getTime())/86400000<=DUE_SOON_DAYS?'DUE_SOON':'OPEN'}
export function campaignProgress(c:Campaign,requirements:FindingRequirement[],findings:Finding[]){const list=requirements.filter(r=>r.campaignId===c.id),satisfied=list.filter(r=>isSatisfied(r,findings)).length;return{total:list.length,satisfied,rate:list.length?Math.min(100,Math.round(satisfied/list.length*100)):0}}
export function contribution(profile:UserProfile,campaign:Campaign,family:FindingFamily){if(!profile.permissions.includes('CONTRIBUTE'))return{allowed:false,reason:'Ce profil ne dispose pas du droit de contribution.'};const audience=campaign.audience.mode==='ALL_INTERNAL'||campaign.audience.roleIds.includes(profile.role)||campaign.audience.profileIds?.includes(profile.id);if(!audience)return{allowed:false,reason:'La campagne est visible mais son audience ne comprend pas ce profil.'};const familyRole=family.allowedRoles.includes(profile.role)||(campaign.audience.mode==='ALL_INTERNAL'&&family.configuration.simpleForAllInternal);if(!familyRole)return{allowed:false,reason:'Cette famille est accessible en lecture seule pour ce métier.'};return{allowed:true,reason:''}}
export function canEditFinding(profile:UserProfile,finding:Finding){return profile.role==='TRANSVERSE_MANAGER'||finding.createdBy===profile.id}
export function validateFinding(family:FindingFamily,answers:FindingAnswer[],photos:number,finalize:boolean){if(!finalize)return[];const errors:string[]=[];for(const q of family.questions){const visible=!q.conditionalOn||answers.some(a=>a.questionId===q.conditionalOn!.questionId&&a.value===q.conditionalOn!.equals);const answer=answers.find(a=>a.questionId===q.id);if(visible&&q.required&&!answer?.notApplicable&&(answer?.value===null||answer?.value===undefined||answer?.value===''))errors.push(`Réponse requise : ${q.label}`)}if(family.photoRequirement==='REQUIRED'&&!photos)errors.push('Une photo est obligatoire pour finaliser ce constat.');return errors}
export function history(profile:UserProfile,action:ChangeHistoryEntry['action'],changedFields:string[],previousValues?:Record<string,Serializable>,newValues?:Record<string,Serializable>):ChangeHistoryEntry{return{id:`hist-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,date:new Date().toISOString(),userId:profile.id,userName:profile.displayName,action,changedFields,previousValues,newValues}}
export const stateLabels:Record<RequirementState,string>={UPCOMING:'À venir',OPEN:'Ouvert',DUE_SOON:'Échéance proche',OVERDUE:'En retard',SATISFIED:'Satisfait'};
export const roleLabels:Record<UserProfile['role'],string>={AGENCY_FIELD_AGENT:'Agent de terrain',TENANT_RELATIONS_SPECIALIST:'Spécialiste relations locataires',TRANSVERSE_MANAGER:'Responsable transverse',INTERNAL_EMPLOYEE:'Collaboratrice interne'};
