import type {FindingAnswer,FindingFamily} from '../../types';
type Props={family:FindingFamily;answers:FindingAnswer[];onChange:(answers:FindingAnswer[])=>void;disabled?:boolean};
const value=(answers:FindingAnswer[],id:string)=>answers.find(a=>a.questionId===id);
const set=(answers:FindingAnswer[],onChange:Props['onChange'],questionId:string,v:string|number|boolean|null,notApplicable=false)=>onChange([...answers.filter(a=>a.questionId!==questionId),{questionId,value:v,notApplicable}]);
function Mowing(p:Props){const q=p.family.questions[0],current=value(p.answers,q.id)?.value;return <fieldset disabled={p.disabled}><legend>{q.label}</legend><div className="answer-grid">{q.options!.map(o=><button type="button" aria-pressed={current===o} key={o} onClick={()=>set(p.answers,p.onChange,q.id,o)}>{o}</button>)}</div></fieldset>}
function Cleanliness(p:Props){return <div className="form-stack">{p.family.questions.map(q=>{const a=value(p.answers,q.id);return <fieldset disabled={p.disabled} key={q.id}><legend>{q.label}</legend><div className="rating">{[1,2,3,4,5].map(n=><button type="button" aria-label={`${q.label} : ${n}`} aria-pressed={a?.value===n&&!a.notApplicable} onClick={()=>set(p.answers,p.onChange,q.id,n)} key={n}>{n}</button>)}<button type="button" className="na" aria-pressed={a?.notApplicable} onClick={()=>set(p.answers,p.onChange,q.id,null,true)}>Non concerné</button></div></fieldset>})}<small>1 = très dégradé · 3 = moyen · 5 = très propre</small></div>}
function Display(p:Props){return <div className="form-stack">{['rules','schedule','contacts'].map(key=>{const present=value(p.answers,`${key}_present`)?.value;const label=p.family.questions.find(q=>q.id===`${key}_present`)!.label.replace(' — présent','');return <fieldset disabled={p.disabled} key={key}><legend>{label}</legend><div className="answer-grid"><button type="button" aria-pressed={present===true} onClick={()=>set(p.answers,p.onChange,`${key}_present`,true)}>Présent</button><button type="button" aria-pressed={present===false} onClick={()=>set(p.answers,p.onChange,`${key}_present`,false)}>Absent</button></div>{present===true&&<div className="answer-grid nested"><button type="button" aria-pressed={value(p.answers,`${key}_compliant`)?.value===true} onClick={()=>set(p.answers,p.onChange,`${key}_compliant`,true)}>Conforme</button><button type="button" aria-pressed={value(p.answers,`${key}_compliant`)?.value===false} onClick={()=>set(p.answers,p.onChange,`${key}_compliant`,false)}>Non conforme</button></div>}{present===false&&<p className="absent">Absent — conformité non demandée</p>}</fieldset>})}</div>}
function Election(p:Props){const done=value(p.answers,'display_done')?.value;return <fieldset disabled={p.disabled}><legend>Réalisation de l’affichage</legend><div className="answer-grid"><button type="button" aria-pressed={done===true} onClick={()=>set(p.answers,p.onChange,'display_done',true)}>Affichage réalisé</button><button type="button" aria-pressed={done===false} onClick={()=>set(p.answers,p.onChange,'display_done',false)}>Affichage non réalisé</button></div>{done===true&&<label className="field">Date et heure de réalisation<input type="datetime-local" value={String(value(p.answers,'displayed_at')?.value||'').slice(0,16)} onChange={e=>set(p.answers,p.onChange,'displayed_at',e.target.value)}/></label>}</fieldset>}
const registry:Record<FindingFamily['formType'],(props:Props)=>JSX.Element>={MOWING:Mowing,CLEANLINESS_RATING:Cleanliness,DOCUMENT_DISPLAY:Display,ELECTION_DISPLAY:Election};
export function FamilyForm(props:Props){const Component=registry[props.family.formType];return <Component {...props}/>}
